---
title: "Survival Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(survival)
library(ggplot2)
library(dplyr)
library(ggfortify)

official_indir <- '/Users/grahamgumbert/Library/CloudStorage/Box-Box/PROJECT 06023: MolClocks/Neuroblastoma_Paper/Datasets'
proj_dir <- file.path(official_indir, 'TARGET')

clinical <- read.table(file.path(proj_dir, 'clinical.annotated.survival.tsv'), sep='\t', header=T)
```

# Kaplan-meier curves

```{r kaplan-meier, message = F}
# Restrict columns
survival_data <- data.frame(
  Patient=clinical$submitter_id,
  event=as.numeric(clinical$vital_status == 'Dead'),
  time=clinical$days_to_follow_up,
  c_beta=clinical$c_beta,
  inss_stage=clinical$inss_stage,
  cog_neuroblastoma_risk_group=clinical$cog_neuroblastoma_risk_group,
  mitosis_karyorrhexis_index=clinical$mitosis_karyorrhexis_index,
  inpc_grade=clinical$inpc_grade,
  gender=clinical$gender
  )
any(is.na(survival_data))
# survival_data <- survival_data[complete.cases(survival_data), ]

sprintf('%d samples available', nrow(survival_data))

# KM curves

##############################################################
#################### stratify by c_beta ######################
##############################################################

# Quartiles
survival_data %>%
    mutate(quartile = ntile(c_beta, 4)) -> survival_data
survival_data$Stratum <- c('c_beta 1st Quartile',
                           'c_beta 2nd Quartile',
                           'c_beta 3rd Quartile',
                           'c_beta 4th Quartile')[survival_data$quartile]
autoplot(survfit(Surv(time, event) ~ Stratum, data=survival_data))

##############################################################
############ Stratify by other clinical variables ############
##############################################################

autoplot(survfit(Surv(time, event) ~ inss_stage, data=survival_data))

table(survival_data$cog_neuroblastoma_risk_group)
autoplot(survfit(Surv(time, event) ~ cog_neuroblastoma_risk_group, data=survival_data))

autoplot(survfit(Surv(time, event) ~ mitosis_karyorrhexis_index, data=survival_data))

autoplot(survfit(Surv(time, event) ~ inpc_grade, data=survival_data))

autoplot(survfit(Surv(time, event) ~ gender, data=survival_data))
```

# Cox-models

```{r cox-models, message = F}
summary(coxph(Surv(time, event) ~ c_beta, data = survival_data))

summary(coxph(Surv(time, event) ~ c_beta + cog_neuroblastoma_risk_group, data = survival_data))
```

```{r}
# install.packages("survminer")  # if not yet installed
library(survminer)

# Fit a Cox model
fit_coxph <- coxph(Surv(time, event) ~ c_beta + cog_neuroblastoma_risk_group,
                   data = survival_data)

# Create a forest plot
ggforest(fit_coxph, data = survival_data)


```
