---
title: "NBL Proliferation Scores"
date: "`r Sys.Date()`"
output: html_document
---

# Setup and data import

```{r, message = F}
library(dplyr)
library(GSVA)
library(msigdbr)
library(DESeq2)
library(GSEABase)
library(jsonlite)

getSampleID <- function(s) {
  paste(strsplit(s, "-", fixed = TRUE)[[1]][1:4], collapse = "-")
}

consts <- read_json(file.path(repo_dir, 'config.json'))
proj_dir <- file.path(consts[['official_indir']], 'TARGET')

clinical <- read.table(file.path(proj_dir, 'clinical.processed.tsv'), sep='\t', header=T)
clinical$in_analysis_dataset <- as.logical(clinical$in_analysis_dataset)
analysis.samples <- clinical$sampleID[clinical$in_analysis_dataset]

expression.data <- readRDS(file.path(proj_dir, 'cohort1.rnaseq_raw_counts.rds'))
expr.sampleIDs <- lapply(colnames(expression.data), getSampleID)
n.overlap <- sum(expr.sampleIDs %in% analysis.samples)
```

There are `r length(analysis.samples)` samples in the TARGET cohort. `r n.overlap` samples have expression data.

# Create normalized DESeq dataset from expression data
```{r}
# Grab gene names
gene_names <- expression.data$gene_name
expression.data <- expression.data[, !(colnames(expression.data) %in% c('gene_name', 'gene_id'))]

sum(duplicated(gene_names))
length(unique(gene_names))

# Prepare data
# Sum counts for duplicate gene names
keep <- !is.na(gene_names) & gene_names != ""
counts_symbol <- rowsum(
  as.matrix(expression.data[keep, ]),
  group = gene_names[keep]
)
metadata <- data.frame(row.names = colnames(counts_symbol))

# Create DESeq dataset
dds <- DESeqDataSetFromMatrix(
  countData = round(counts_symbol),        # genes x samples
  colData = metadata,
  design = ~ 1
)

# Normalize expression
vsd <- vst(dds, blind = TRUE)
expr <- assay(vsd)
```

# Calculate and save expressions scores for hallmark pathways

```{r}
# Get gene sets
hallmark <- msigdbr(species = "Homo sapiens", collection = "H")
gene_sets <- split(hallmark$gene_symbol, hallmark$gs_name)

# GSVA
gsc <- GeneSetCollection(list(
  GeneSet(
    geneIds = gene_sets[["HALLMARK_E2F_TARGETS"]],
    setName = "HALLMARK_E2F_TARGETS",
    geneIdType = SymbolIdentifier()
  ),
  GeneSet(
    geneIds = gene_sets[["HALLMARK_G2M_CHECKPOINT"]],
    setName = "HALLMARK_G2M_CHECKPOINT",
    geneIdType = SymbolIdentifier()
  )
))
param <- ssgseaParam(
  exprData=as.matrix(expr),
  geneSets = gsc
  )
scores <- t(gsva(
  param,
  verbose = TRUE
))

saveRDS(scores, file.path(proj_dir, 'TARGET_ssGSEA_scores.rds'))
write.table(scores, file.path(proj_dir, 'TARGET_ssGSEA_scores.tsv'),
            quote=F, sep='\t')
```
