---
title: "Survival Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(survival)
library(ggplot2)
library(dplyr)
library(ggfortify)
library(survminer)
library(kableExtra)

official_indir <- '/Users/danielmonyak/Library/CloudStorage/Box-Box/PROJECT 06023: MolClocks/Neuroblastoma_Paper/Datasets'
proj_dir <- file.path(official_indir, 'TARGET')

clinical <- read.table(file.path(proj_dir, 'clinical.annotated.survival.tsv'), sep='\t', header=T)
```

# Prepare data

```{r kaplan-meier, message = F}
sf = 0.6
label_fontsize <- 16
p_val_size <- 4
  
# Restrict columns
survival_data <- data.frame(
  Patient=clinical$submitter_id,
  event=as.numeric(clinical$vital_status == 'Dead'),
  time=clinical$days_to_follow_up / 365,
  mitotic.age=clinical$phi,                # Use phi as tumor mitotic age
  inss_stage=clinical$inss_stage,
  cog_neuroblastoma_risk_group=clinical$cog_neuroblastoma_risk_group,
  mitosis_karyorrhexis_index=clinical$mitosis_karyorrhexis_index,
  inpc_grade=clinical$inpc_grade,
  gender=clinical$gender
  )
any(is.na(survival_data))

sprintf('%d samples available', nrow(survival_data))

# KM curves

#########################################################
############### stratify by mitotic.age #################
#########################################################

# Halves
survival_data <- survival_data %>%
    mutate(dichom = ntile(mitotic.age, 2),
    dichom = factor(dichom, levels = c(1, 2), labels = c("Young", "Old")))
```


# Kaplan-meier curves {.tabset .tabset-fade}

## All tumors 
```{r all-tumors-km}
#######################################
########### All tumors ################
#######################################

fit <- survfit(Surv(time, event) ~ dichom, data=survival_data)

# Compute p-value
logrank <- survdiff(Surv(time, event) ~ dichom, data = survival_data)
p_val <- 1 - pchisq(logrank$chisq, df = length(logrank$n) - 1)
p_label <- paste0("P = ", signif(p_val, 2))

# Plot with customizations and p-value
km_plot <- autoplot(fit) +
  ylim(0, 1) +
  labs(
    x = "Time since diagnosis (years)",
    y = "Survival",
    title = sprintf('All tumors (N = %d)', sum(logrank$n))
  ) +
  annotate("text", x = 12, y = 0.9, label = p_label, size = sf * p_val_size) +
  theme_classic() +
  theme(plot.title = element_text(size=sf * label_fontsize, hjust = 0.5),
        axis.title = element_text(size=sf * label_fontsize),
        legend.title = element_blank(),
        legend.text = element_text(size=sf * label_fontsize * 0.8),
        legend.position = c(0.03, 0.05),  # bottom-left corner
        legend.justification = c(0, 0)
        ) +
  scale_color_discrete(labels = c(
    sprintf('Young tumors (n = %d)', logrank$n[['dichom=Young']]),
    sprintf('Old tumors (n = %d)', logrank$n[['dichom=Old']])
  )) +
  scale_fill_discrete(labels = c(
    sprintf('Young tumors (n = %d)', logrank$n[['dichom=Young']]),
    sprintf('Old tumors (n = %d)', logrank$n[['dichom=Old']])
  ))

ggsave(file.path('figures', "km_plot.svg"), km_plot, width = sf * 6, height = sf * 5, dpi = 800, device='svg')

km_plot
```

## Stage 4 tumors

```{r stage-4-km}
####################################
########### Stage 4 ################
####################################



# Halves
# survival_data <- survival_data[survival_data$inss_stage == 'Stage 4',] %>%
#     mutate(dichom = ntile(mitotic.age, 2),
#     dichom = factor(dichom, levels = c(1, 2), labels = c("Young", "Old")))

fit<-survfit(Surv(time, event) ~ dichom, data=survival_data, subset = inss_stage == "Stage 4")

# Compute p-value
logrank <- survdiff(Surv(time, event) ~ dichom, data=survival_data, subset = inss_stage == "Stage 4")
p_val <- 1 - pchisq(logrank$chisq, df = length(logrank$n) - 1)
p_label <- paste0("P = ", signif(p_val, 2))

# Plot with customizations and p-value
km_plot_4 <- autoplot(fit) +
  ylim(0, 1) +
  labs(
    x = "Time since diagnosis (years)",
    y = "Survival",
    title = sprintf('Stage 4 tumors (N = %d)', sum(logrank$n))
  ) +
  annotate("text", x = 12, y = 0.9, label = p_label, size = sf * p_val_size) +
  theme_classic() +
  theme(plot.title = element_text(size=sf * label_fontsize, hjust = 0.5),
        axis.title = element_text(size=sf * label_fontsize),
        legend.title = element_blank(),
        legend.text = element_text(size=sf * label_fontsize * 0.8),
        legend.position = c(0.03, 0.05),  # bottom-left corner
        legend.justification = c(0, 0)
        ) +
  scale_color_discrete(labels = c(
    sprintf('Young tumors (n = %d)', logrank$n[['dichom=Young']]),
    sprintf('Old tumors (n = %d)', logrank$n[['dichom=Old']])
  )) +
  scale_fill_discrete(labels = c(
    sprintf('Young tumors (n = %d)', logrank$n[['dichom=Young']]),
    sprintf('Old tumors (n = %d)', logrank$n[['dichom=Old']])
  ))

ggsave(file.path('figures', "km_plot_4.svg"), km_plot_4, width = sf * 6, height = sf * 5, dpi = 800, device='svg')

km_plot_4
```

```{r dumped-code, echo=F, eval=F}
# survival_data$Stratum <- c('mitotic.age 1st Quartile',
#                            'mitotic.age 2nd Quartile',
#                            'mitotic.age 3rd Quartile',
#                            'mitotic.age 4th Quartile')[survival_data$quartile]
# autoplot(survfit(Surv(time, event) ~ Stratum, data=survival_data))

##############################################################
############ Stratify by other clinical variables ############
##############################################################



# autoplot(survfit(Surv(time, event) ~ inss_stage, data=survival_data))
# 
# table(survival_data$cog_neuroblastoma_risk_group)
# autoplot(survfit(Surv(time, event) ~ cog_neuroblastoma_risk_group, data=survival_data))
# 
# autoplot(survfit(Surv(time, event) ~ mitosis_karyorrhexis_index, data=survival_data))
# 
# autoplot(survfit(Surv(time, event) ~ inpc_grade, data=survival_data))
# 
# autoplot(survfit(Surv(time, event) ~ gender, data=survival_data))
```

# Cox-models {.tabset .tabset-fade}

## Predict only with tumor mitotic age

```{r cox-models, message = F}
coxResultsTable <- function(mod) {
  modsum <- summary(mod)
  coefs <- as.data.frame(modsum$coefficients) # Get coefficients
  conf.int <- as.data.frame(modsum$conf.int)
  # colnames(coef_table) <- c("Coef", "Exp(Coef)", "SE(Coef)", "z", "p")
  coef_table <- cbind(coefs, conf.int)
  names(coef_table)[which(names(coef_table) == 'Pr(>|z|)')] = 'p'
  # Reformat
  format(coef_table, digits=2)
}


# mod <- coxph(Surv(time, event) ~ mitotic.age, data = survival_data, subset = inss_stage == "Stage 4")

mod.allTumors <- coxph(Surv(time, event) ~ mitotic.age,
                                   data = survival_data)


coef_table.allTumors <- coxResultsTable(mod.allTumors)

# Display as a kable table
kable(coef_table.allTumors, caption = "Cox Proportional Hazards Model Summary") %>%
  kable_styling(full_width = FALSE, position = "left")


schoenfeld_test.allTumors <- cox.zph(mod.allTumors)
print(schoenfeld_test.allTumors)
# Display results

# Plot residuals for proportional hazards check
plot(schoenfeld_test.allTumors)
```

## Predict only with tumor mitotic age for STAGE 4 tumors

```{r cox-models-stage4, message = F}

mod.stage4 <- coxph(Surv(time, event) ~ mitotic.age,
                       data = survival_data,
                       subset = inss_stage == "Stage 4")


coef_table.stage4 <- coxResultsTable(mod.stage4)

# Display as a kable table
kable(coef_table.stage4, caption = "Cox Proportional Hazards Model Summary, stage 4 tumors") %>%
  kable_styling(full_width = FALSE, position = "left")


schoenfeld_test.stage4 <- cox.zph(mod.stage4)
print(schoenfeld_test.stage4)
# Display results

# Plot residuals for proportional hazards check
plot(schoenfeld_test.stage4)
```

## Predict with tumor mitotic age and COG risk group

```{r check-confounding}
mod.mitotic.age.COG <- coxph(Surv(time, event) ~ mitotic.age + cog_neuroblastoma_risk_group, data = survival_data)

# print(summary())


coef_table.mitotic.age.COG <- coxResultsTable(mod.mitotic.age.COG)

# Display as a kable table
kable(coef_table.mitotic.age.COG, caption = "Cox Proportional Hazards Model Summary") %>%
  kable_styling(full_width = FALSE, position = "left")


schoenfeld_test.mitotic.age.COG <- cox.zph(mod.mitotic.age.COG)
print(schoenfeld_test.mitotic.age.COG)
# Display results

# Plot residuals for proportional hazards check
plot(schoenfeld_test.mitotic.age.COG)
```


